budgetta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budgetta_app.urls')),
    path('users/', include('users.urls')),
]

budgetta_app/urls.py
from django.urls import path, include

from budgetta_app import views

app_name = 'budgetta_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('transactions/', views.transactions, name='transactions'),
    path('new_transaction/', views.new_transaction, name='new_transaction'),
    path('categories/', views.categories, name='categories'),
    path('new_categroy/', views.new_category, name='new_category'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('edit_transaction/<int:transaction_id>/', views.edit_transaction, name='edit_transaction'),
    path('edit_transaction_modal/', views.edit_transaction_modal, name='edit_transaction_modal'),
]

users/urls.py
from django.urls import path, include

from users import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

budgetta_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    limit = models.PositiveSmallIntegerField(null=True)
    is_expense = models.BooleanField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    name = models.CharField(max_length=150)
    amount = models.IntegerField()
    is_expense = models.BooleanField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

budgetta_app/forms.py
from django import forms

from .models import Transaction, Category


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['name', 'amount', 'is_expense', 'category']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(owner=self.user)

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'limit', 'is_expense']

budgetta_app/views/categories_view.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.
from django.shortcuts import render, redirect
from budgetta_app.forms import CategoryForm
from budgetta_app.models import Category
from budgetta_app.utils import shared_utils


@login_required
def categories(request):
    """show all categories"""
    categories = Category.objects.filter(owner=request.user).order_by('date')
    expense_sum = 0
    income_sum = 0
    for category in categories:
        if category.is_expense:
            expense_sum += category.limit
        else:
            income_sum += category.limit
    total_expenses = shared_utils.get_total_expenses(request.user)
    expected_expenses = shared_utils.get_expected_expenses(request.user)
    context = {'categories': categories, 'expense_sum': expense_sum, 'income_sum': income_sum,
               'total_expenses': total_expenses,
               'expected_expenses': expected_expenses}
    return render(request, 'budgetta_app/categories.html', context)


@login_required
def new_category(request):
    """add new category"""
    if request.method != 'POST':
        form = CategoryForm()
    else:
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.owner = request.user
            category.save()
            return redirect('budgetta_app:categories')
    total_expenses = shared_utils.get_total_expenses(request.user)
    expected_expenses = shared_utils.get_expected_expenses(request.user)
    context = {'form': form,
               'total_expenses': total_expenses,
               'expected_expenses': expected_expenses}
    return render(request, 'budgetta_app/new_category.html', context)


@login_required
def edit_category(request, category_id):
    """edit category"""
    category = Category.objects.get(owner=request.user, id=category_id)
    if category.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = CategoryForm(instance=category)
    elif request.POST['edit'] == 'submit':
        form = CategoryForm(instance=category, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('budgetta_app:categories')
    elif request.POST['edit'] == 'delete':
        category.delete()
        return redirect('budgetta_app:categories')
    total_expenses = shared_utils.get_total_expenses(request.user)
    expected_expenses = shared_utils.get_expected_expenses(request.user)
    context = {'category': category, 'form': form,
               'total_expenses': total_expenses,
               'expected_expenses': expected_expenses}
    return render(request, 'budgetta_app/edit_category.html', context)

budgetta_app/views/index_view.py
from budgetta_app.utils import shared_utils
from django.shortcuts import render


def index(request):
    if request.user.is_authenticated:
        category_by_sum = shared_utils.get_category_by_sum(request.user)
        expense_list = []
        income_list = []
        total_expenses = shared_utils.get_total_expenses(request.user)
        expected_expenses = shared_utils.get_expected_expenses(request.user)

        for category in category_by_sum:
            if category['is_expense']:
                expense_list.append(category)
            else:
                income_list.append(category)

        context = {'expense_list': expense_list,
                   'income_list': income_list,
                   'total_expenses': total_expenses,
                   'expected_expenses': expected_expenses}
    else:
        context = {}

    return render(request, 'budgetta_app/index.html', context)

budgetta_app/views/transactions_view.py
import datetime

from django.contrib.auth.decorators import login_required
from budgetta_app.forms import TransactionForm
from budgetta_app.models import Transaction, Category
from budgetta_app.utils import shared_utils
from django.shortcuts import render, redirect


@login_required
def transactions(request):
    """show all transactions"""
    today = datetime.datetime.now()
    transactions_query_set = Transaction.objects.filter(owner=request.user, date__year=today.year,
                                              date__month=today.month).order_by('-date')
    categories = Category.objects.filter(owner=request.user)
    expenses = []
    incomes = []
    for transaction in transactions_query_set:
        transaction.date = transaction.date.strftime("%d-%m-%Y")
        if transaction.is_expense:
            expenses.append(transaction)
        else:
            incomes.append(transaction)

    total_expenses = shared_utils.get_total_expenses(request.user)
    expected_expenses = shared_utils.get_expected_expenses(request.user)

    context = {'expenses': expenses, 'incomes': incomes, 'categories': categories,
               'total_expenses': total_expenses,
               'expected_expenses': expected_expenses}
    return render(request, 'budgetta_app/transactions.html', context)


@login_required
def new_transaction(request):
    """add new transaction"""
    if request.method != 'POST':
        form = TransactionForm(user=request.user)
    else:
        form = TransactionForm(user=request.user, data=request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.owner = request.user
            transaction.save()
            return redirect('budgetta_app:transactions')
    total_expenses = shared_utils.get_total_expenses(request.user)
    expected_expenses = shared_utils.get_expected_expenses(request.user)
    context = {'form': form,
               'total_expenses': total_expenses,
               'expected_expenses': expected_expenses}
    return render(request, 'budgetta_app/new_transaction.html', context)


def edit_transaction(request, transaction_id):
    """edit transaction"""
    transaction = Transaction.objects.get(owner=request.user, id=transaction_id)
    if request.method != 'POST':
        form = TransactionForm(instance=transaction, user=request.user)
    elif request.POST['edit'] == 'submit':
        form = TransactionForm(instance=transaction, data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('budgetta_app:transactions')
    elif request.POST['edit'] == 'delete':
        transaction.delete()
        return redirect('budgetta_app:transactions')
    total_expenses = shared_utils.get_total_expenses(request.user)
    expected_expenses = shared_utils.get_expected_expenses(request.user)
    context = {'transaction': transaction, 'form': form,
               'total_expenses': total_expenses,
               'expected_expenses': expected_expenses}
    return render(request, 'budgetta_app/edit_transaction.html', context)


def edit_transaction_modal(request):
    """edit transaction from modal"""
    transaction_id = request.POST['transaction']
    transaction = Transaction.objects.get(owner=request.user, id=transaction_id)
    if request.POST['edit'] == 'delete':
        transaction.delete()
        return redirect('budgetta_app:transactions')
    if request.POST['edit'] == 'submit':
        form = TransactionForm(instance=transaction, data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('budgetta_app:transactions')
    return redirect('budgetta_app:transactions')

budgetta_app/templates/budgetta_app/base.html
{% load bootstrap4 %}
{% load static %}

{% load django_template_maths %}
{% load filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
       shrink-to-fit=no">
    <title>Budgetta - budget manager</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% block stylesheet %}{% static "budgetta_app/css/style.css" %}{% endblock %}">
    <script src="{% static "budgetta_app/js/bs-table.js" %}"></script>
    <script src="{% static "budgetta_app/js/scripts.js" %}"></script>
    <link href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table-locale-all.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/extensions/mobile/bootstrap-table-mobile.min.js"></script>

</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'budgetta_app:index'%}">Budgetta</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'budgetta_app:transactions' %}">transactions</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'budgetta_app:categories' %}">categories</a></li>
        </ul>
        {% endif %}
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text">Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
    {% if user.is_authenticated %}
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">

            <div class="progress">
                <div class="{{ total_expenses.sum|mul:100 |div:expected_expenses.sum | get_progress_status }}" role="progressbar"
                     style="width: {{ total_expenses.sum|mul:100 |div:expected_expenses.sum }}%"
                     aria-valuenow={{total_expenses.sum}} aria-valuemin="0" aria-valuemax={{expected_expenses.sum}}>
                    {{ total_expenses.sum }} / {{ expected_expenses.sum }}
                </div>
            </div>
        </div>
    </main>
    {% endif %}
   <main role="main" class="container">
     <div class="pb-2 mb-2 border-bottom">
         {% block page_header %}{% endblock page_header %}
     </div>
     <div>
         {% block content %}{% endblock content %}
       </div>
     </main>

</body>
</html>

budgetta_app/templates/budgetta_app/categories.html
{% extends "budgetta_app/base.html" %}
{% block page_header %}
<h1>Categories</h1>
{% endblock page_header %}
{% block content %}
<button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#categoryModal">
  add category
</button>
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
{% include 'budgetta_app/new_category_modal.html' %}
</div>
<br>
<br>
<p> expected expense: {{ expense_sum }}</p>
<p>expected income: {{ income_sum }} </p>
{% if categories|length > 0 %}
<div class="table-sort" style="overflow: auto; height: 350px;">
<table class="table" class="table-sort" data-toggle="table" data-mobile-responsive="true">
  <thead class="thead-light">
    <tr>
      <th data-field="name"  scope="col">name</th>
      <th data-field="limit" data-sortable="true" scope="col">limit</th>
      <th data-field="type" data-sortable="true" scope="col">type</th>
    </tr>
  </thead>
  <tbody>
  {% for category in categories %}
    <tr>
      <th scope="row"><a href="{% url 'budgetta_app:edit_category' category.id %}">{{ category.name }}</a></th>
      <td>{{ category.limit}}</td>
      {% if category.is_expense %}
        <td>expense</td>
      {% else %}
        <td>income</td>
      {% endif %}
    </tr>

    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<p>No categories have been added yet.</p>
{% endif %}

{% endblock content %}

budgetta_app/templates/budgetta_app/edit_category.html
{% extends "budgetta_app/base.html" %}

{% block content %}

<p>Edit category:</p>

<form action="{% url 'budgetta_app:edit_category' category.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="edit" value="submit">Save changes</button>
    <button name="edit" value="delete">delete category</button>
</form>

{% endblock content %}

budgetta_app/templates/budgetta_app/edit_transaction.html
{% extends "budgetta_app/base.html" %}

{% block content %}

<p>Edit transaction:</p>

<form action="{% url 'budgetta_app:edit_transaction' transaction.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="edit" value="submit">Save changes</button>
    <button name="edit" value="delete">delete transaction</button>
</form>

{% endblock content %}

budgetta_app/templates/budgetta_app/edit_transaction_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {% block content %}
            <form action="{% url 'budgetta_app:edit_transaction_modal' %}" method='post'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="transactionName">name</label>
                    <input name="name" type="text" autocomplete="off" class="form-control" id="transactionName"
                           aria-describedby="transactionHelp">
                </div>
                <div class="form-group">
                    <label for="transactionAmount">amount</label>
                    <input name="amount" type="number" autocomplete="off" class="form-control" id="transactionAmount">
                    <input name="transaction" style="display: none;" type="text" id="transactionId">
                    {% if is_expense_val == "on" %}
                        <input name="is_expense" style="display: none;" type="checkbox" checked='true' class="form-check-input" >
                    {% endif %}
                </div>

               <div class="form-group">
                    <label for="categoryText">category</label>
                    <select name="category" class="form-control" id="categoryText">
                        {% for category in categories %}
                        {% if is_expense_val == "on" %}
                            {% if category.is_expense %}
                            <option value= {{ category.id }} >{{ category.name }}</option>
                            {% endif %}
                        {% else %}
                            {% if not category.is_expense %}
                            <option value= {{ category.id }} >{{ category.name }}</option>
                            {% endif %}
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button name="edit" value="delete" class="btn btn-primary">delete</button>
                    <button name="edit" value="submit" type="submit" class="btn btn-primary">submit</button>
                </div>
            </form>
            {% endblock content %}
        </div>
    </div>
</div>

budgetta_app/templates/budgetta_app/index.html
{% extends "budgetta_app/base.html" %}
{% load bootstrap4 %}
{% load django_template_maths %}
{% load filters %}

{% block page_header %}
{% if user.is_anonymous %}
<div class="jumbotron">
    <h1 class="display-3">Manage your budget</h1>

    <p class="lead">manage your budget by tracking your expenses and finance transactions</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
       role="button">Register &raquo;</a>
</div>
{% endif %}
{% endblock page_header %}

{% block content %}
{% if user.is_authenticated %}

<h3><p> expense:</p></h3>
{% if expense_list|length > 0 %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col" width="20%">Category</th>
        <th scope="col" width="80%">Status</th>
    </tr>
    </thead>
    <tbody>
    {% for expense in expense_list %}
    <tr>
        <th scope="row" width="20%">{{ expense.category__name}}</th>
        <td colspan="2" width="80%">
            <div class="progress">
                <div class=" {{ expense.total_price|mul:100 |div:expense.category__limit | get_progress_status }} "  role="progressbar"
                     style="width: {{ expense.total_price|mul:100 |div:expense.category__limit}}%"
                     aria-valuenow={{expense.total_price}} aria-valuemin="0" aria-valuemax={{expense.category__limit}}>
                    {{ expense.total_price }} / {{ expense.category__limit }}
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>No expenses have been added yet.</p>
{% endif %}
<h3><p> income:</p></h3>
{% if income_list|length > 0 %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col" width="20%">Category</th>
        <th scope="col" width="80%">Status</th>
    </tr>
    </thead>
    <tbody>
    {% for income in income_list %}
    <tr>
        <th scope="row" width="20%">{{ income.category__name}}</th>
        <td colspan="2" width="80%">
            <div class="progress">
                <div class="{{ income.total_price|mul:100 |div:income.category__limit | get_progress_status }}" role="progressbar"
                     style="width: {{ income.total_price|mul:100 |div:income.category__limit}}%"
                     aria-valuenow={{income.total_price}} aria-valuemin="0" aria-valuemax={{income.category__limit}}>
                    {{ income.total_price }} / {{ income.category__limit }}
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>No income have been added yet.</p>
{% endif %}

{% endif %}
{% endblock content %}

budgetta_app/templates/budgetta_app/new_category.html
{% extends "budgetta_app/base.html" %}

{% block content %}
<p>Add categroy:</p>

<form action="{% url 'budgetta_app:new_category' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add</button>
</form>

{% endblock content %}

budgetta_app/templates/budgetta_app/new_category_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {% block content %}
            <form action="{% url 'budgetta_app:new_category' %}" method='post'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="categoryName">name</label>
                    <input name="name" type="text" autocomplete="off" class="form-control" id="categoryName"
                           aria-describedby="transactionHelp">
                </div>
                <div class="form-group">
                    <label for="limitText">amount</label>
                    <input name="limit" type="number" autocomplete="off" class="form-control" id="limitText">
                </div>
                <div class="form-check">
                    <input name="is_expense" type="checkbox" class="form-check-input" id="IseExpenseCheck">
                    <label class="form-check-label" for="IseExpenseCheck">expense</label>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">submit</button>
                </div>
            </form>
            {% endblock content %}
        </div>
    </div>
</div>

budgetta_app/templates/budgetta_app/new_transaction.html
{% extends "budgetta_app/base.html" %}

{% block content %}
<p>Add transaction:</p>

<form action="{% url 'budgetta_app:new_transaction' %}" autocomplete="off" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add</button>
</form>


{% endblock content %}

budgetta_app/templates/budgetta_app/new_transaction_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {% block content %}
            <form action="{% url 'budgetta_app:new_transaction' %}" autocomplete="off" method='post'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="transactionName">name</label>
                    <input name="name" type="text" class="form-control" id="transactionName"
                           aria-describedby="transactionHelp">
                </div>
                <div class="form-group">
                    <label for="amountText">amount</label>
                    <input name="amount" type="number" class="form-control" id="amountText">
                </div>
                <input name="is_expense" type="text" hidden="true" class="form-check-input" id="IseExpenseCheck"
                       value={{ is_expense_val }}>
                <div class="form-group">
                    <label for="categoryText">category</label>
                    <select class="form-control" id="categoryText" name="category">
                        {% for category in categories %}
                        {% if is_expense_val == "on" %}
                            {% if category.is_expense %}
                            <option value={{ category.id }}>{{ category.name }}</option>
                            {% endif %}
                        {% else %}
                            {% if not category.is_expense %}
                            <option value={{ category.id }}>{{ category.name }}</option>
                            {% endif %}
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">submit</button>
                </div>
            </form>
            {% endblock content %}
        </div>
    </div>
</div>

budgetta_app/templates/budgetta_app/transactions.html
{% extends "budgetta_app/base.html" %}

{% block page_header %}
<h1>Transactions</h1>
{% endblock page_header %}
{% block content %}
<p>Expenses:</p>

<button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#expenseModal">
  add expense
</button>
<div class="modal fade" id="expenseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
{% include 'budgetta_app/new_transaction_modal.html' with is_expense_val='on' %}
</div>

<div class="modal fade" id="editExpenseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
{% include 'budgetta_app/edit_transaction_modal.html' with is_expense_val='on' %}
</div>

<div class="modal fade" id="editIncomeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
{% include 'budgetta_app/edit_transaction_modal.html' with is_expense_val='off' %}
</div>

<br>
<br>

{% if expenses|length > 0 %}
<div class="table-sort" style="display: block;height: 300px; overflow-y: auto">
<table class="table-sort" data-toggle="table" data-mobile-responsive="true">
  <thead class="thead-light">
    <tr>
      <th data-field="name"  scope="col" >name</th>
      <th data-field="category" data-sortable="true" scope="col" scope="col">category</th>
      <th data-field="amount" data-sortable="true" scope="col">amount</th>
      <th data-field="date" data-sortable="true" scope="col">date</th>
    </tr>
  </thead>


  <tbody >
  {% for expense in expenses %}
    <tr>
      <th scope="row"><a href="#" onclick="javascript:showExpense('{{ expense.name }}', '{{ expense.amount }}', '{{ expense.category_id }}', '{{ expense.id }}')">{{ expense.name }}</a></th>
      <td>{{ expense.category }}</td>
      <td>{{ expense.amount }}</td>
      <td>{{ expense.date }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>
</div>
    {% else %}
    <p>No expense transactions have been added yet.</p>
    {% endif %}


<p>Income:</p>

  <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#incomeModal">
  add income
</button>
<div class="modal fade" id="incomeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
{% include 'budgetta_app/new_transaction_modal.html' %}
</div>
<br>
<br>



{% if incomes|length > 0 %}
<div class="table-sort" style="display: block;height: 300px; overflow-y: auto">
<table class="table-sort"  data-toggle="table" data-mobile-responsive="true">
  <thead class="thead-light">
    <tr>
      <th data-field="name" scope="col">name</th>
      <th data-field="category" data-sortable="true" scope="col">category</th>
      <th data-field="amount" data-sortable="true" scope="col">amount</th>
      <th data-field="date" data-sortable="true" scope="col">date</th>
    </tr>
  </thead>
  <tbody>
  {% for income in incomes %}
    <tr>
      <th scope="row"><a href="#" onclick="javascript:showIncome('{{ income.name }}', '{{ income.amount }}', '{{ income.category_id }}', '{{ income.id }}')">{{ income.name }}</a></th>
      <td>{{ income.category}}</td>
      <td>{{ income.amount}}</td>
      <td>{{ income.date}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
    {% else %}
    <p>No income transactions have been added yet.</p>
    {% endif %}
{% endblock content %}